version: '3'

services:
  douban-notion:
    image: ${DOCKER_REGISTRY}/douban-notion:latest
    container_name: douban-notion
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - DOUBAN_BID=${DOUBAN_BID}
      - DOUBAN_LL=${DOUBAN_LL}
      - DOUBAN_DBCL2=${DOUBAN_DBCL2}
      - DOUBAN_CK=${DOUBAN_CK}
    volumes:
      - douban-chrome-data:/root/.config/chromium  # 持久化Chrome配置，提高稳定性
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    shm_size: 1gb  # 增加共享内存大小，解决Chrome崩溃问题
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 512m

volumes:
  douban-chrome-data: 