version: '3'

services:
  douban-notion-api:
    image: ${IMAGE_NAME:-ghcr.io/your-username/douban-notion:latest}
    container_name: douban-notion-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - DOUBAN_BID=${DOUBAN_BID:-}
      - DOUBAN_LL=${DOUBAN_LL:-}
      - DOUBAN_DBCL2=${DOUBAN_DBCL2:-}
      - DOUBAN_CK=${DOUBAN_CK:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 