version: '3'

services:
  douban-notion-sync:
    image: ${DOCKER_USERNAME}/douban-notion-sync:latest
    container_name: douban-notion-sync
    restart: unless-stopped
    ports:
      - "6000:6000"
    environment:
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_TOKEN=${NOTION_TOKEN}
    volumes:
      - ./logs:/app/logs
    networks:
      - douban-net

networks:
  douban-net:
    driver: bridge 