version: '3'

services:
  douban-notion:
    image: ${DOCKER_REGISTRY}/douban-notion:latest
    container_name: douban-notion
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - DOUBAN_BID=${DOUBAN_BID}
      - DOUBAN_LL=${DOUBAN_LL}
      - DOUBAN_DBCL2=${DOUBAN_DBCL2}
      - DOUBAN_CK=${DOUBAN_CK}
      # 设置Chrome的无头模式参数
      - CHROME_NO_SANDBOX=true
      - WDM_LOCAL=1
      - WDM_CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
    volumes:
      # 持久化Chrome配置和缓存
      - ./chrome_data:/root/.config/chrome
      - ./chrome_cache:/root/.cache/google-chrome
      # 共享时区设置
      - /etc/localtime:/etc/localtime:ro
    # 增加共享内存大小，提高Chrome稳定性
    shm_size: 1gb 